name: Agentbeats Automated Release

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'pyproject.toml'
      - 'MANIFEST.in'
      - 'README.md'
  release:
    types: [ published ]

jobs:
  bump-and-tag:
    name: Bump version & create GitHub Release
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' &&
             !startsWith(github.event.head_commit.message, 'chore(release') }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with: { fetch-depth: 0 }

      - uses: actions/setup-python@v4
        with: { python-version: '3.x' }

      - run: pip install python-semantic-release

      - name: Bump version, commit & tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: semantic-release version

  publish-to-pypi:
    name: Build & Publish to PyPI
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.tag_name }}
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with: { python-version: '3.x' }

      - run: pip install build twine

      - run: python -m build --sdist --wheel

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: python -m twine upload dist/*
